;; Keywords: factorization roca math crypto number-theory
;; Integer-factorization routines for ROCA weak-key detection and factorization.
;; Targets RSA primes generated by Infineon chips.
;; References:
;; - The ROCA paper: "The Return of Coppersmith's Attack: Practical
;;   Factorization of Widely Used RSA Moduli".
module std.math.crypto.factorization.roca(ROCA_E, roca_prime_set, roca_prime_power_divisors, roca_multiplicative_order, roca_compute_max_M, roca_greedy_find_M, roca_discrete_log, roca_check_prime, roca_factor, roca_factor_with_params, roca_factor_with_prime_info, roca_detect, coppersmith_approximation)
use std.math.nt
use std.math.scalar (log2)

def ROCA_E = 65537

fn roca_prime_power_divisors(any M) list {
   "Return all prime-power divisors p^i from the factorization of M."
   def fs = factor(M, false, false)
   mut out = list(0)
   mut i = 0
   while i < fs.len {
      def p, e = fs.get(i).get(0), fs.get(i).get(1)
      mut pp = 1
      mut j = 0
      while j < e {
         pp = pp * p
         out = out.append(pp)
         j += 1
      }
      i += 1
   }
   sort(out)
}

fn roca_multiplicative_order(any g, any m) any {
   "Return the multiplicative order of g modulo m, or nil if gcd(g,m) != 1."
   if m <= 1 || gcd(g, m) != 1 { return nil }
   mut x = mod(g, m)
   mut ord = 1
   def cap = m + 1
   while x != 1 && ord <= cap {
      x = mod(x * g, m)
      ord += 1
   }
   (x == 1) ? ord : nil
}

fn roca_compute_max_M(any M, any ord_) any {
   "ROCA Algorithm 2: remove prime-power factors whose 65537 order does not divide ord_."
   mut out = M
   def pps = roca_prime_power_divisors(M)
   mut i = 0
   while i < pps.len {
      def pp = pps.get(i)
      def ordp = roca_multiplicative_order(ROCA_E, pp)
      if ordp != nil && ord_ % ordp != 0 { out = out / pp }
      i += 1
   }
   out
}

fn _roca_ratio_score(any ord, any ord2, any M, any M2) f64 {
   if ord2 <= 0 || M2 <= 0 || M == M2 { return -1.0 }
   (log2(float(ord)) - log2(float(ord2))) / (log2(float(M)) - log2(float(M2)))
}

fn roca_greedy_find_M(any n, any M) any {
   "Greedily choose the reduced ROCA modulus M' while log2(M') remains at least log2(n)/4."
   mut cur_M = M
   mut ord = roca_multiplicative_order(ROCA_E, cur_M)
   if ord == nil { return cur_M }
   while true {
      mut best_r = 0.0
      mut best_ord = ord
      mut best_M = cur_M
      def pps = roca_prime_power_divisors(ord)
      mut i = 0
      while i < pps.len {
         def pp = pps.get(i)
         def ord2 = ord / pp
         def M2 = roca_compute_max_M(cur_M, ord2)
         def r = _roca_ratio_score(ord, ord2, cur_M, M2)
         if r > best_r {
            best_r = r
            best_ord = ord2
            best_M = M2
         }
         i += 1
      }
      if log2(float(best_M)) < log2(float(n)) / 4.0 { return cur_M }
      if best_M == cur_M || best_ord == ord { return cur_M }
      cur_M = best_M
      ord = best_ord
   }
   cur_M
}

fn roca_discrete_log(any value, any M, any g=65537) any {
   "Brute-force discrete log in the small ROCA subgroup generated by g modulo M."
   def ord = roca_multiplicative_order(g, M)
   if ord == nil { return nil }
   def target = mod(value, M)
   mut x, a = 1, 0
   while a < ord {
      if x == target { return a }
      x = mod(x * g, M)
      a += 1
   }
   nil
}

fn roca_prime_set(any m) list {
   "Compute the set {65537^a mod m : a >= 0}.
   This is the set of valid residues for ROCA-vulnerable primes mod m."
   mut residues = [1]
   mut val = 1
   while true {
      val = (val * ROCA_E) % m
      if val == 1 { break }
      residues = residues.append(val)
   }
   residues
}

fn roca_check_prime(any p) bool {
   "Check if a single prime p is ROCA-vulnerable.
   Tests whether p mod m is in the valid set for m in {3, 5, 7, 11, 13, 17, 19, 23}.
   Returns true if p appears to be ROCA-vulnerable."
   def m_list = [3, 5, 7, 11, 13, 17, 19, 23]
   def nm = m_list.len
   mut i = 0
   while i < nm {
      mut m = m_list.get(i)
      def residues = roca_prime_set(m)
      def nr = residues.len
      def p_mod = p % m
      mut found = false
      mut j = 0
      while j < nr {
         if residues.get(j) == p_mod {
            found = true
            break
         }
         j += 1
      }
      if !found { return false }
      i += 1
   }
   true
}

fn roca_factor(any n) any {
   "Attempt to factor n using small built-in ROCA primorials.
   Searches ROCA residue classes around sqrt(n) ; use roca_factor_with_params
   when the input provides the original primorial.
   Returns [p, q] or nil if factoring fails."
   def m_list = [3, 5, 7, 11, 13, 17, 19, 23]
   mut M, i = 1, 0
   while i < m_list.len {
      mut m = m_list.get(i)
      M = M * m
      i += 1
   }
   roca_factor_with_params(n, M, 0, 0, ROCA_E, 100000)
}

fn _roca_search_residue_near_sqrt(any n, any M, any residue, int search_range) any {
   def a_init = isqrt(n)
   mut p0 = a_init - mod(a_init - residue, M)
   if p0 < Z(2) { p0 = residue }
   mut k = 0
   while k <= search_range {
      def step = Z(k) * Z(M)
      def p1 = p0 + step
      def p2 = p0 - step
      if p1 > Z(1) && p1 < n && mod(n, p1) == Z(0) {
         mut q = n / p1
         return (p1 < q) ? [p1, q] : [q, p1]
      }
      if k > 0 && p2 > Z(1) && p2 < n && mod(n, p2) == Z(0) {
         mut q = n / p2
         return (p2 < q) ? [p2, q] : [q, p2]
      }
      k += 1
   }
   nil
}

fn roca_factor_with_params(any n, any M, any m=0, any t=0, any g=65537, int search_range=100000) any {
   "Factor a ROCA modulus with a caller-provided primorial M.
   Follows the ROCA setup: compute M', solve N = g^c mod M',
   enumerate compatible a' values, then search p = M'k + g^a' near sqrt(n).
   m and t are accepted for callers that pass the published ROCA parameter set."
   def M2 = roca_greedy_find_M(n, M)
   def c = roca_discrete_log(n, M2, g)
   if c == nil { return nil }
   def ord = roca_multiplicative_order(g, M2)
   if ord == nil { return nil }
   mut a = c / 2
   def end_a = (c + ord) / 2 + 1
   while a <= end_a {
      def residue = power_mod(g, a, M2)
      def res = _roca_search_residue_near_sqrt(n, M2, residue, search_range)
      if res != nil { return res }
      a += 1
   }
   nil
}

fn roca_factor_with_prime_info(any n, any M, any a) any {
   "Factor n given knowledge of the modulus M and exponent a.
   p = k*M + (65537^a mod M). Search for the correct k.
   Returns [p, q] or nil."
   def target_res = power_mod(ROCA_E, a, M)
   def a_sqrt = isqrt(n)
   def k_start = (a_sqrt - target_res) / Z(M)
   def k_range = 500000
   mut k = 0
   while k < k_range {
      def p1, p2 = k_start + Z(k), k_start - Z(k)
      if p1 > Z(1) {
         def candidate = p1 * Z(M) + target_res
         if candidate > Z(1) && candidate < n && mod(n, candidate) == Z(0) {
            mut q = n / candidate
            return (candidate < q) ? [candidate, q] : [q, candidate]
         }
      }
      if k > 0 && p2 > Z(1) {
         def candidate = p2 * Z(M) + target_res
         if candidate > Z(1) && candidate < n && mod(n, candidate) == Z(0) {
            mut q = n / candidate
            return (candidate < q) ? [candidate, q] : [q, candidate]
         }
      }
      k += 1
   }
   nil
}

fn roca_detect(any n) bool {
   "Detect whether n may be ROCA-vulnerable by checking
   if n mod small primes is consistent with both factors
   being in the ROCA residue sets.
   Returns true if n is likely ROCA-vulnerable."
   def m_list = [3, 5, 7, 11, 13, 17, 19, 23]
   def nm = m_list.len
   mut i = 0
   while i < nm {
      mut m = m_list.get(i)
      def residues = roca_prime_set(m)
      def nr = residues.len
      def n_mod = n % m
      mut possible = false
      mut j = 0
      while j < nr {
         mut k = 0
         while k < nr {
            if mod(residues.get(j) * residues.get(k), m) == n_mod {
               possible = true
               break
            }
            k += 1
         }
         if possible { break }
         j += 1
      }
      if !possible { return false }
      i += 1
   }
   true
}

fn coppersmith_approximation(any n, int bits_p) any {
   "Bounded close-factor search near sqrt(n).
   Returns [p, q] or nil."
   def a_init = isqrt(n)
   def search_window = 1 << (bits_p / 4)
   mut offset = 0
   while offset < search_window {
      def p1, p2 = a_init + Z(offset), a_init - Z(offset)
      if p1 > Z(1) && mod(n, p1) == Z(0) {
         mut q = n / p1
         return (p1 < q) ? [p1, q] : [q, p1]
      }
      if offset > 0 && p2 > Z(1) && mod(n, p2) == Z(0) {
         mut q = n / p2
         return (p2 < q) ? [p2, q] : [q, p2]
      }
      offset += 1
   }
   nil
}
