;; Keywords: lattice ntru math crypto number-theory
;; Lattice routines for NTRU lattice construction and recovery.
;; Reference:
;; - https://www.ntru.org/f/ntru-20190330.pdf
;; References:
;; - std.math.crypto.lattice
;; - std.math.crypto
module std.math.crypto.lattice.ntru(ntru_centered, ntru_circulant_rows, ntru_cyclic_convolution, ntru_poly_neg_mod, ntru_poly_xgcd_mod, ntru_cyclic_inverse_mod, ntru_public_key_lattice_basis, ntru_is_ternary, ntru_slice, ntru_bits_to_text, ntru_decrypt_blocks_with_f, ntru_recover_ternary_key_rows, ntru_recover_text_from_public_key_lattice, ntru_recover_text_from_known_plaintext)
use std.core
use std.math.nt (Z)
use std.math.integer (inverse_mod)
use std.math.crypto.poly (poly_mod_add, poly_mod_div, poly_mod_mul)
use std.math.crypto.lattice.lll as lllmod

fn _ntru_has_len(list xs, int n) bool { n >= 0 && xs.len >= n }

fn _ntru_zeroes(int n) list {
   if(n <= 0){ return [] }
   mut out = []
   for _ in 0..n - 1 { out = out.append(0) }
   out
}

fn ntru_centered(any x, any modulus) any {
   "Return the centered representative of `x mod modulus`."
   def v = x % modulus
   v > modulus / 2 ? v - modulus : v
}

fn _ntru_mod(any x, any modulus) any {
   def v = x % modulus
   v < 0 ? v + modulus : v
}

fn ntru_circulant_rows(list poly, int n) list {
   "Return the row-circulant matrix generated by `poly`."
   if(n <= 0 || !_ntru_has_len(poly, n)){ return [] }
   mut rows = []
   for i in 0..n - 1 {
      mut row = []
      for j in 0..n - 1 { row = row.append(poly[(j - i + n) % n]) }
      rows = rows.append(row)
   }
   rows
}

fn ntru_cyclic_convolution(list a, list b, int n, any modulus) list {
   "Multiply two cyclic polynomials modulo `x^n - 1` and `modulus`."
   if(n <= 0 || !_ntru_has_len(a, n) || !_ntru_has_len(b, n)){ return [] }
   mut out = _ntru_zeroes(n)
   for i in 0..n - 1 {
      if(a[i] == 0){ continue }
      for j in 0..n - 1 {
         def k = (i + j) % n
         out[k] = _ntru_mod(out[k] + a[i] * b[j], modulus)
      }
   }
   out
}

fn ntru_poly_neg_mod(list a, any modulus) list {
   "Negate a polynomial coefficient-wise modulo `modulus`."
   mut out = []
   for v in a { out = out.append((0 - v) % modulus) }
   out
}

fn _ntru_poly_trim(list a) list {
   mut end = a.len
   while(end > 0 && a[end - 1] == 0){ end -= 1 }
   mut out = []
   mut i = 0
   while(i < end){
      out = out.append(a[i])
      i += 1
   }
   out
}

fn ntru_poly_xgcd_mod(list a, list b, any modulus) list {
   "Extended gcd for modular polynomial coefficients; returns `[g, s]` with `s*a = g mod b`."
   mut r0 = _ntru_poly_trim(a)
   mut r1 = _ntru_poly_trim(b)
   mut s0 = [1]
   mut s1 = [0]
   mut steps = 0
   while(r1.len > 0 && !(r1.len == 1 && r1[0] == 0) && steps < 4096){
      def div = poly_mod_div(r0, r1, modulus)
      def qq = div[0]
      def rr = _ntru_poly_trim(div[1])
      def ss = poly_mod_add(s0, ntru_poly_neg_mod(poly_mod_mul(qq, s1, modulus), modulus), modulus)
      r0 = r1
      r1 = rr
      s0 = s1
      s1 = ss
      steps += 1
   }
   if(r0.len == 0 || steps >= 4096){ return [[], []] }
   def lc = r0[r0.len - 1]
   if(lc != 1){
      def inv_lc = inverse_mod(lc, modulus)
      mut nr0 = []
      mut ns0 = []
      for v in r0 { nr0 = nr0.append((v * inv_lc) % modulus) }
      for v in s0 { ns0 = ns0.append((v * inv_lc) % modulus) }
      r0 = nr0
      s0 = ns0
   }
   [r0, s0]
}

fn ntru_cyclic_inverse_mod(list f, int n, any modulus) list {
   "Return `f^-1 mod(x^n - 1, modulus)`, or `[]` when not invertible."
   if(n <= 0 || !_ntru_has_len(f, n)){ return [] }
   mut mod_poly = [(-1) % modulus]
   for _ in 1..n - 1 { mod_poly = mod_poly.append(0) }
   mod_poly = mod_poly.append(1)
   def res = ntru_poly_xgcd_mod(f, mod_poly, modulus)
   def g = res[0]
   def s = res[1]
   if(g.len != 1){ return [] }
   def div = poly_mod_div(s, mod_poly, modulus)
   def inv = div[1]
   mut out = []
   for i in 0..n - 1 { out = out.append(i < inv.len ? inv[i] : 0) }
   out
}

fn ntru_public_key_lattice_basis(list h, int n, any p, any q) list {
   "Build the scaled `2n x 2n` row-circulant NTRU public-key lattice basis `[qI | 0; p^-1*h | I]`."
   if(n <= 0 || !_ntru_has_len(h, n)){ return [0, 0, []] }
   def alpha = inverse_mod(p, q)
   mut h3 = []
   for i in 0..n - 1 { h3 = h3.append(ntru_centered(alpha * h[i], q)) }
   def H = ntru_circulant_rows(h3, n)
   mut rows = []
   for i in 0..n - 1 {
      mut row = []
      for j in 0..n - 1 { row = row.append(i == j ? q : 0) }
      for _ in 0..n - 1 { row = row.append(0) }
      rows = rows.append(row)
   }
   for i in 0..n - 1 {
      mut row = []
      for j in 0..n - 1 { row = row.append(H[i][j]) }
      for j in 0..n - 1 { row = row.append(i == j ? 1 : 0) }
      rows = rows.append(row)
   }
   [rows.len, rows.len > 0 ? rows[0].len : 0, rows]
}

fn ntru_is_ternary(list row, int start, int stop) bool {
   "Return true when every selected coefficient is in `{-1, 0, 1}`."
   if(start < 0 || stop < start || stop > row.len){ return false }
   for i in start..stop - 1 {
      def v = row[i]
      if(v < -1 || v > 1){ return false }
   }
   true
}

fn _ntru_is_scaled_ternary(list row, int start, int stop, any scale) bool {
   if(start < 0 || stop < start || stop > row.len){ return false }
   for i in start..stop - 1 {
      def v = row[i]
      if(v % scale != 0){ return false }
      def u = v / scale
      if(u < -1 || u > 1){ return false }
   }
   true
}

fn ntru_slice(list row, int start, int stop) list {
   "Slice a row by integer bounds."
   if(start < 0 || stop < start || stop > row.len){ return [] }
   mut out = []
   for i in start..stop - 1 { out = out.append(row[i]) }
   out
}

fn ntru_bits_to_text(list bits) str {
   "Pack a 0/1 bit list as big-endian bytes and return text."
   mut out = ""
   mut i = 0
   while(i + 8 <= bits.len){
      mut byte = Z(0)
      for j in 0..7 { byte = byte * Z(2) + Z(bits[i + j]) }
      if(byte == Z(0)){ break }
      out += chr(int(byte))
      i += 8
   }
   out
}

fn _ntru_text_to_bits(str text) list {
   mut out = []
   mut i = 0
   while(i < text.len){
      def c = int(text[i])
      mut bit = 7
      while(bit >= 0){
         out = out.append((c >> bit) & 1)
         bit -= 1
      }
      i += 1
   }
   out
}

fn _ntru_center_mod_prime_row(list row, any p) list {
   mut out = []
   for v in row {
      def x = v % p
      out = out.append(x > p / 2 ? x - p : x)
   }
   out
}

fn _ntru_modp(any x, any p) any {
   def v = x % p
   v < 0 ? v + p : v
}

fn _ntru_transpose(list rows, int cols) list {
   mut out = []
   if(cols <= 0){ return out }
   for c in 0..cols - 1 {
      mut row = []
      for r in rows { row = row.append(r[c]) }
      out = out.append(row)
   }
   out
}

fn _ntru_nullspace_mod(list rows, int cols, any p) list {
   mut A = []
   for row in rows {
      mut rr = []
      for c in 0..cols - 1 { rr = rr.append(_ntru_modp(row[c], p)) }
      A = A.append(rr)
   }
   mut pivots = []
   mut rank = 0
   mut col = 0
   while(col < cols && rank < A.len){
      mut pivot = rank
      while(pivot < A.len && _ntru_modp(A[pivot][col], p) == 0){ pivot += 1 }
      if(pivot < A.len){
         def tmp = A[rank]
         A[rank] = A[pivot]
         A[pivot] = tmp
         def inv = inverse_mod(_ntru_modp(A[rank][col], p), p)
         for j in 0..cols - 1 { A[rank][j] = _ntru_modp(A[rank][j] * inv, p) }
         mut r = 0
         while(r < A.len){
            if(r != rank){
               def factor = _ntru_modp(A[r][col], p)
               if(factor != 0){
                  for j in 0..cols - 1 { A[r][j] = _ntru_modp(A[r][j] - factor * A[rank][j], p) }
               }
            }
            r += 1
         }
         pivots = pivots.append(col)
         rank += 1
      }
      col += 1
   }
   mut basis = []
   col = 0
   while(col < cols){
      mut is_pivot = false
      for pc in pivots {
         if(pc == col){ is_pivot = true }
      }
      if(!is_pivot){
         mut v = []
         for _ in 0..cols - 1 { v = v.append(0) }
         v[col] = 1
         mut ri = 0
         while(ri < pivots.len){
            v[pivots[ri]] = _ntru_modp(0 - A[ri][col], p)
            ri += 1
         }
         basis = basis.append(v)
      }
      col += 1
   }
   basis
}

fn ntru_decrypt_blocks_with_f(list ciphertexts, list f, int n, any p, any q) str {
   "Decrypt NTRU ciphertext blocks with ternary private key component `f`."
   if(n <= 0 || !_ntru_has_len(f, n)){ return "" }
   def finv = ntru_cyclic_inverse_mod(f, n, p)
   if(finv.len == 0){ return "" }
   mut bits = []
   mut bi = 0
   while(bi < ciphertexts.len){
      def block = ciphertexts[bi]
      if(!_ntru_has_len(block, n)){ return "" }
      mut a = ntru_cyclic_convolution(f, block, n, q)
      for i in 0..n - 1 { a[i] = _ntru_modp(ntru_centered(a[i], q), p) }
      def m = ntru_cyclic_convolution(a, finv, n, p)
      for b in m {
         def bit = _ntru_modp(b, p)
         bits = bits.append(bit)
      }
      bi += 1
   }
   ntru_bits_to_text(bits)
}

fn _ntru_decrypt_block_bits(list block, list f, int n, any p, any q) list {
   if(!_ntru_has_len(block, n) || !_ntru_has_len(f, n)){ return [] }
   def finv = ntru_cyclic_inverse_mod(f, n, p)
   if(finv.len == 0){ return [] }
   mut a = ntru_cyclic_convolution(f, block, n, q)
   for i in 0..n - 1 { a[i] = _ntru_modp(ntru_centered(a[i], q), p) }
   def m = ntru_cyclic_convolution(a, finv, n, p)
   mut bits = []
   for b in m {
      def bit = _ntru_modp(b, p)
      if(bit != 0 && bit != 1){ return [] }
      bits = bits.append(bit)
   }
   bits
}

fn _ntru_bits_prefix_match(list bits, list prefix) bool {
   if(prefix.len == 0){ return true }
   if(bits.len < prefix.len){ return false }
   mut i = 0
   while(i < prefix.len){
      if(bits[i] != prefix[i]){ return false }
      i += 1
   }
   true
}

fn _ntru_neg_vec(list xs) list {
   mut out = []
   for x in xs { out = out.append(0 - x) }
   out
}

fn _ntru_rotate_vec(list xs, int shift) list {
   if(xs.len == 0){ return [] }
   mut out = []
   mut i = 0
   while(i < xs.len){
      out = out.append(xs[(i + shift) % xs.len])
      i += 1
   }
   out
}

fn _ntru_reverse_vec(list xs) list {
   mut out = []
   mut i = xs.len - 1
   while(i >= 0){
      out = out.append(xs[i])
      i -= 1
   }
   out
}

fn _ntru_try_f_variants(list ciphertexts, list f, int n, any p, any q, str needle) str {
   if(ciphertexts.len == 0){ return "" }
   mut prefix = _ntru_text_to_bits(needle)
   if(prefix.len > n){ prefix = ntru_slice(prefix, 0, n) }
   mut mode = 0
   while(mode < 2){
      def shaped = mode == 0 ? f : _ntru_reverse_vec(f)
      mut sign = 0
      while(sign < 2){
         def base = sign == 0 ? shaped : _ntru_neg_vec(shaped)
         mut shift = 0
         while(shift < n){
            def cand = _ntru_rotate_vec(base, shift)
            if(!_ntru_bits_prefix_match(_ntru_decrypt_block_bits(ciphertexts[0], cand, n, p, q), prefix)){
               shift += 1
               continue
            }
            def text = ntru_decrypt_blocks_with_f(ciphertexts, cand, n, p, q)
            if(text.find(needle) >= 0){ return text }
            shift += 1
         }
         sign += 1
      }
      mode += 1
   }
   ""
}

fn _ntru_try_key_row(list row, int n, list ciphertexts, any p, any q, str needle) str {
   if(ntru_is_ternary(row, 0, n) && _ntru_is_scaled_ternary(row, n, 2 * n, p)){
      def text = _ntru_try_f_variants(ciphertexts, ntru_slice(row, 0, n), n, p, q, needle)
      if(text.find(needle) >= 0){ return text }
   }
   if(_ntru_is_scaled_ternary(row, 0, n, p) && ntru_is_ternary(row, n, 2 * n)){
      def text = _ntru_try_f_variants(ciphertexts, ntru_slice(row, n, 2 * n), n, p, q, needle)
      if(text.find(needle) >= 0){ return text }
   }
   if(ntru_is_ternary(row, 0, n) && ntru_is_ternary(row, n, 2 * n)){
      def text = _ntru_try_f_variants(ciphertexts, ntru_slice(row, 0, n), n, p, q, needle)
      if(text.find(needle) >= 0){ return text }
      def alt = _ntru_try_f_variants(ciphertexts, ntru_slice(row, n, 2 * n), n, p, q, needle)
      if(alt.find(needle) >= 0){ return alt }
   }
   ""
}

fn _ntru_scan_rows(list rows, int n, list ciphertexts, any p, any q, str needle) str {
   mut i = 0
   while(i < rows.len){
      def msg = _ntru_try_key_row(rows[i], n, ciphertexts, p, q, needle)
      if(msg.len > 0){ return msg }
      i += 1
   }
   ""
}

fn _ntru_is_private_key_row(list row, int n, any p) bool {
   (ntru_is_ternary(row, 0, n) && _ntru_is_scaled_ternary(row, n, 2 * n, p)) ||
   (_ntru_is_scaled_ternary(row, 0, n, p) && ntru_is_ternary(row, n, 2 * n)) ||
   (ntru_is_ternary(row, 0, n) && ntru_is_ternary(row, n, 2 * n))
}

fn _ntru_scan_key_rows(list rows, int n, any p) list {
   mut out = []
   mut i = 0
   while(i < rows.len){
      if(_ntru_is_private_key_row(rows[i], n, p)){ out = out.append(rows[i]) }
      i += 1
   }
   out
}

fn _ntru_known_plaintext_candidates(list ciphertext, list known_bits, int n, any p, any q) list {
   if(ciphertext.len < n || known_bits.len < n){ return [] }
   mut diff = []
   for i in 0..n - 1 { diff = diff.append((ntru_centered(ciphertext[i], q) - known_bits[i]) % p) }
   def rows = ntru_circulant_rows(diff, n)
   def kernel = _ntru_nullspace_mod(_ntru_transpose(rows, n), n, p)
   mut candidates = []
   for row in kernel {
      def f = _ntru_center_mod_prime_row(row, p)
      if(ntru_is_ternary(f, 0, n)){ candidates = candidates.append(f) }
   }
   candidates
}

fn ntru_recover_text_from_known_plaintext(list ciphertexts, int n, any p, any q, str known_prefix, str needle="MSG{") str {
   "Recover NTRU plaintext when known plaintext covers a full block, using a GF(p) convolution kernel for `f`."
   if(ciphertexts.len == 0){ return "" }
   def known_bits = _ntru_text_to_bits(known_prefix)
   def candidates = _ntru_known_plaintext_candidates(ciphertexts[0], known_bits, n, p, q)
   for f in candidates {
      def text = ntru_decrypt_blocks_with_f(ciphertexts, f, n, p, q)
      if(text.find(needle) >= 0){ return text }
   }
   ""
}

fn ntru_recover_ternary_key_rows(list h, int n, any p, any q, int chunk_steps=50000, int chunks=12, any delta=0.99, any eta=0.51) list {
   "Run bounded native LLL slices on the public-key lattice and return ternary candidate rows seen during reduction."
   mut basis = ntru_public_key_lattice_basis(h, n, p, q)
   mut found = []
   mut pass = 0
   while(pass < chunks){
      def rows = basis[2]
      found = _ntru_scan_key_rows(rows, n, p)
      if(found.len > 0){ return found }
      def rep = lllmod.lll_reduce_bounded_report(basis, chunk_steps, delta, "bounded-int-no-transform", eta)
      basis = rep.get("basis")
      pass += 1
   }
   def reduced = lllmod.lll(basis, delta, "ny", eta)
   found = _ntru_scan_key_rows(reduced[2], n, p)
   found
}

fn ntru_recover_text_from_public_key_lattice(list h, list ciphertexts, int n, any p, any q, str needle="MSG{", int chunk_steps=50000, int chunks=12) str {
   "Recover an NTRU plaintext by reducing the public-key lattice in bounded native chunks and testing ternary key rows."
   if(needle.len * 8 >= n){
      def known_hit = ntru_recover_text_from_known_plaintext(ciphertexts, n, p, q, needle, needle)
      if(known_hit.len > 0){ return known_hit }
   }
   mut basis = ntru_public_key_lattice_basis(h, n, p, q)
   mut pass = 0
   while(pass <= chunks){
      def hit = _ntru_scan_rows(basis[2], n, ciphertexts, p, q, needle)
      if(hit.len > 0){ return hit }
      if(pass == chunks){ break }
      def rep = lllmod.lll_reduce_bounded_report(basis, chunk_steps, 0.99, "bounded-int-no-transform", 0.51)
      basis = rep.get("basis")
      pass += 1
   }
   def live_rows = lllmod.lll_find_ntru_key_rows(basis, n, p, chunk_steps * max(1, chunks / 2), 0.99, 0.51)
   def live_hit = _ntru_scan_rows(live_rows, n, ciphertexts, p, q, needle)
   if(live_hit.len > 0){ return live_hit }
   ""
}
