#include "ast.c"

#include "bigint.c"
#include "core.c"
#include "simmd.c"
#include "ffi.c"
#include "ffigates.c"
#include "gc.c"
#include "math.c"
#include "memory.c"
#include "os.c"
#include "string.c"
