#include "jit_symbols.h"
#include <stdint.h>
#include <llvm-c/ExecutionEngine.h>
#include <llvm-c/Core.h>

// Runtime symbols declarations
extern int64_t rt_malloc(int64_t);
extern int64_t rt_init_str(int64_t, int64_t);
extern int64_t rt_free(int64_t);
extern int64_t rt_realloc(int64_t, int64_t);
extern int64_t rt_memcpy(int64_t, int64_t, int64_t);
extern int64_t rt_memset(int64_t, int64_t, int64_t);
extern int64_t rt_memcmp(int64_t, int64_t, int64_t);
extern int64_t rt_load8_idx(int64_t, int64_t);
extern int64_t rt_store8_idx(int64_t, int64_t, int64_t);
extern int64_t rt_load8(int64_t);
extern int64_t rt_store8(int64_t, int64_t);
extern int64_t rt_load64(int64_t);
extern int64_t rt_store64(int64_t, int64_t);
extern int64_t rt_syscall(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_execve(int64_t, int64_t, int64_t);
extern int64_t rt_exit(int64_t);
extern int64_t rt_dlopen(int64_t, int64_t);
extern int64_t rt_dlsym(int64_t, int64_t);
extern int64_t rt_dlclose(int64_t);
extern int64_t rt_dlerror(void);
extern int64_t rt_call0(int64_t);
extern int64_t rt_call1(int64_t, int64_t);
extern int64_t rt_call2(int64_t, int64_t, int64_t);
extern int64_t rt_call3(int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call4(int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call5(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call6(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call7(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call8(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call9(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call10(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call11(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call12(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_call13(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_set_args(int64_t, int64_t, int64_t);
extern int64_t rt_argc(void);
extern int64_t rt_argv(int64_t);
extern int64_t rt_envp(void);
extern int64_t rt_envc(void);
extern int64_t rt_errno(void);
extern int64_t rt_parse_ast(int64_t source_ptr);
extern int64_t rt_globals(void);
extern int64_t rt_set_globals(int64_t);
extern int64_t rt_panic(int64_t);
extern int64_t rt_set_panic_env(int64_t);
extern int64_t rt_clear_panic_env(void);
extern int64_t rt_jmpbuf_size(void);
extern int64_t rt_get_panic_val(void);
extern int64_t rt_thread_spawn(int64_t, int64_t);
extern int64_t rt_thread_join(int64_t);
extern int64_t rt_mutex_new(void);
extern int64_t rt_mutex_lock64(int64_t);
extern int64_t rt_mutex_unlock64(int64_t);
extern int64_t rt_mutex_free(int64_t);
extern int64_t rt_load16_idx(int64_t, int64_t);
extern int64_t rt_load32_idx(int64_t, int64_t);
extern int64_t rt_load64_idx(int64_t, int64_t);
extern int64_t rt_store16_idx(int64_t, int64_t, int64_t);
extern int64_t rt_store32_idx(int64_t, int64_t, int64_t);
extern int64_t rt_store64_idx(int64_t, int64_t, int64_t);
extern int64_t rt_sys_read_off(int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_sys_write_off(int64_t, int64_t, int64_t, int64_t);
extern int64_t rt_add(int64_t, int64_t);
extern int64_t rt_sub(int64_t, int64_t);
extern int64_t rt_mul(int64_t, int64_t);
extern int64_t rt_div(int64_t, int64_t);
extern int64_t rt_mod(int64_t, int64_t);
extern int64_t rt_and(int64_t, int64_t);
extern int64_t rt_or(int64_t, int64_t);
extern int64_t rt_xor(int64_t, int64_t);
extern int64_t rt_shl(int64_t, int64_t);
extern int64_t rt_shr(int64_t, int64_t);
extern int64_t rt_not(int64_t);
extern int64_t rt_is_int(int64_t);
extern int64_t rt_is_ptr(int64_t);
extern int64_t rt_ptr_add(int64_t, int64_t);
extern int64_t rt_ptr_sub(int64_t, int64_t);
extern int64_t rt_to_int(int64_t);
extern int64_t rt_from_int(int64_t);
extern int64_t rt_to_str(int64_t);
extern int64_t rt_load16(int64_t);
extern int64_t rt_store16(int64_t, int64_t);
extern int64_t rt_load32(int64_t);
extern int64_t rt_store32(int64_t, int64_t);
extern int64_t rt_str_concat(int64_t, int64_t);
extern int64_t rt_eq(int64_t, int64_t);
extern int64_t rt_lt(int64_t, int64_t);
extern int64_t rt_le(int64_t, int64_t);
extern int64_t rt_gt(int64_t, int64_t);
extern int64_t rt_ge(int64_t, int64_t);
extern int64_t rt_kwarg(int64_t, int64_t);
extern int64_t rt_flt_box_val(int64_t);
extern int64_t rt_flt_unbox_val(int64_t);
extern int64_t rt_rand64(void);
extern int64_t rt_srand(int64_t);
extern int64_t rt_flt_add(int64_t, int64_t);
extern int64_t rt_flt_sub(int64_t, int64_t);
extern int64_t rt_flt_mul(int64_t, int64_t);
extern int64_t rt_flt_div(int64_t, int64_t);
extern int64_t rt_flt_lt(int64_t, int64_t);
extern int64_t rt_flt_gt(int64_t, int64_t);
extern int64_t rt_flt_eq(int64_t, int64_t);
extern int64_t rt_flt_from_int(int64_t);
extern int64_t rt_flt_to_int(int64_t);
extern int64_t rt_flt_trunc(int64_t);
extern int64_t rt_sleep(int64_t);

void register_jit_symbols(LLVMExecutionEngineRef ee, LLVMModuleRef mod){
	#define MAP(name, fn_ptr) do { \
		LLVMValueRef val = LLVMGetNamedFunction(mod, name); \
		if (val) { \
			LLVMAddGlobalMapping(ee, val, (void*)fn_ptr); \
		} \
	} while(0)
	MAP("rt_ptr_add", rt_ptr_add);
	MAP("rt_ptr_sub", rt_ptr_sub);
	MAP("rt_malloc", rt_malloc);
	MAP("rt_init_str", rt_init_str);
	MAP("rt_free", rt_free);
	MAP("rt_realloc", rt_realloc);
	MAP("rt_load8_idx", rt_load8_idx);
	MAP("rt_load16_idx", rt_load16_idx);
	MAP("rt_load32_idx", rt_load32_idx);
	MAP("rt_load64_idx", rt_load64_idx);
	MAP("rt_store8_idx", rt_store8_idx);
	MAP("rt_store16_idx", rt_store16_idx);
	MAP("rt_store32_idx", rt_store32_idx);
	MAP("rt_store64_idx", rt_store64_idx);
	MAP("rt_sys_read_off", rt_sys_read_off);
	MAP("rt_sys_write_off", rt_sys_write_off);
	MAP("rt_load8", rt_load8);
	MAP("rt_store8", rt_store8);
	MAP("rt_load64", rt_load64);
	MAP("rt_store64", rt_store64);
	MAP("rt_syscall", rt_syscall);
	MAP("rt_execve", rt_execve);
	MAP("rt_exit", rt_exit);
	MAP("rt_add", rt_add);
	MAP("rt_sub", rt_sub);
	MAP("rt_mul", rt_mul);
	MAP("rt_div", rt_div);
	MAP("rt_mod", rt_mod);
	MAP("rt_and", rt_and);
	MAP("rt_or", rt_or);
	MAP("rt_xor", rt_xor);
	MAP("rt_shl", rt_shl);
	MAP("rt_shr", rt_shr);
	MAP("rt_not", rt_not);
	MAP("rt_is_int", rt_is_int);
	MAP("rt_is_ptr", rt_is_ptr);
	MAP("rt_to_int", rt_to_int);
	MAP("rt_from_int", rt_from_int);
	MAP("rt_to_str", rt_to_str);
	MAP("rt_load16", rt_load16);
	MAP("rt_store16", rt_store16);
	MAP("rt_load32", rt_load32);
	MAP("rt_store32", rt_store32);
	MAP("rt_str_concat", rt_str_concat);
	MAP("rt_eq", rt_eq);
	MAP("rt_lt", rt_lt);
	MAP("rt_le", rt_le);
	MAP("rt_gt", rt_gt);
	MAP("rt_ge", rt_ge);
	MAP("rt_flt_box_val", rt_flt_box_val);
	MAP("rt_flt_unbox_val", rt_flt_unbox_val);
	MAP("rt_flt_add", rt_flt_add);
	MAP("rt_flt_sub", rt_flt_sub);
	MAP("rt_flt_mul", rt_flt_mul);
	MAP("rt_flt_div", rt_flt_div);
	MAP("rt_flt_lt", rt_flt_lt);
	MAP("rt_flt_gt", rt_flt_gt);
	MAP("rt_flt_eq", rt_flt_eq);
	MAP("rt_flt_from_int", rt_flt_from_int);
	MAP("rt_flt_to_int", rt_flt_to_int);
	MAP("rt_flt_trunc", rt_flt_trunc);
	MAP("rt_sleep", rt_sleep);
	MAP("rt_dlsym", rt_dlsym);
	MAP("rt_dlopen", rt_dlopen);
	MAP("rt_dlclose", rt_dlclose);
	MAP("rt_dlerror", rt_dlerror);
	MAP("rt_kwarg", rt_kwarg);
	MAP("rt_call0", rt_call0);
	MAP("rt_call1", rt_call1);
	MAP("rt_call2", rt_call2);
	MAP("rt_call3", rt_call3);
	MAP("rt_call4", rt_call4);
	MAP("rt_call5", rt_call5);
	MAP("rt_call6", rt_call6);
	MAP("rt_call7", rt_call7);
	MAP("rt_call8", rt_call8);
	MAP("rt_call9", rt_call9);
	MAP("rt_call10", rt_call10);
	MAP("rt_call11", rt_call11);
	MAP("rt_call12", rt_call12);
	MAP("rt_call13", rt_call13);
	MAP("rt_set_args", rt_set_args);
	MAP("rt_argc", rt_argc);
	MAP("rt_argv", rt_argv);
	MAP("rt_envp", rt_envp);
	MAP("rt_envc", rt_envc);
	MAP("rt_errno", rt_errno);
	MAP("rt_parse_ast", rt_parse_ast);
	MAP("rt_globals", rt_globals);
	MAP("rt_set_globals", rt_set_globals);
	MAP("rt_panic", rt_panic);
	MAP("rt_set_panic_env", rt_set_panic_env);
	MAP("rt_clear_panic_env", rt_clear_panic_env);
	MAP("rt_jmpbuf_size", rt_jmpbuf_size);
	MAP("rt_get_panic_val", rt_get_panic_val);
	MAP("rt_thread_spawn", rt_thread_spawn);
	MAP("rt_thread_join", rt_thread_join);
	MAP("rt_mutex_new", rt_mutex_new);
	MAP("rt_mutex_lock64", rt_mutex_lock64);
	MAP("rt_mutex_unlock64", rt_mutex_unlock64);
	MAP("rt_mutex_free", rt_mutex_free);
	#undef MAP
}
