use std.core
use std.core.reflect
use std.math.big
use std.math.nt (Z)

def a = bf_from_float(1.5)
def b = bf_from_float(2.25)
assert(is_bigfloat(a), "native tag")
assert(__tagof(a) == __runtime_tag("bigfloat"), "runtime tag")
assert(type(a) == "bigfloat", "type")
assert(bf_precision(a) == 256, "default precision")
def addv = bf_to_float(bf_add(a, b))
assert(addv >= 3.75 - 1e-14 && addv <= 3.75 + 1e-14, "add")
def subv = bf_to_float(bf_sub(b, a))
assert(subv >= 0.75 - 1e-14 && subv <= 0.75 + 1e-14, "sub")
def mulv = bf_to_float(bf_mul(a, b))
assert(mulv >= 3.375 - 1e-14 && mulv <= 3.375 + 1e-14, "mul")
def divv = bf_to_float(bf_div(b, a))
assert(divv >= 1.5 - 1e-14 && divv <= 1.5 + 1e-14, "div")
def sqrtv = bf_to_float(bf_sqrt(bf_from_int(2)))
assert(sqrtv >= 1.4142135623730951 - 1e-14 && sqrtv <= 1.4142135623730951 + 1e-14, "sqrt")
def powv = bf_to_float(bf_pow_int(a, 3))
assert(powv >= 3.375 - 1e-14 && powv <= 3.375 + 1e-14, "pow positive")
def negpowv = bf_to_float(bf_pow_int(bf_from_int(2), -3))
assert(negpowv >= 0.125 - 1e-14 && negpowv <= 0.125 + 1e-14, "pow negative")
assert(bf_eq(bf_from_int(12), bf_add(bf_from_int(7), bf_from_int(5))), "exact add")
assert(bf_eq(bf_from_int(35), bf_mul(bf_from_int(7), bf_from_int(5))), "exact mul")
assert(bf_eq(bf_one(), BF_SCALE), "compat one")
assert(bf_to_str(a) == "1.5", "string")
assert(to_str(a) == "1.5", "generic string")
def wide = bf_with_precision(Z(2)^Z(300), 512)
assert(bf_precision(wide) == 512, "wide precision")
assert(bf_eq(bf_div(wide, wide), bf_with_precision(1, 512)), "wide division")
print("✓ native bigfloat tests passed")
