;; Keywords: engine state viewer selection transform os ui render scene
;; Central engine viewer state for selection, transform modes, panels, and runtime toggles.
;; References:
;; - std.os.ui.render.scene
;; - std.os.ui.render.viewer.runtime
module std.os.ui.render.viewer.engine.state *
use std.core
use std.os.ui.render.matrix as rmat

mut int: APP_MSAA = 4
mut bool: APP_VSYNC = false
mut bool: APP_FILTER_LINEAR = false
mut list: APP_BG = [0.002, 0.002, 0.005, 1.0]
mut bool: APP_WIRE = false
mut bool: APP_STATS = true
mut bool: print_to_stdout = false
mut any: win = 0
mut any: cam = 0
mut any: camthreed = 0
mut f64: _cam_px = 0.0
mut f64: _cam_py = 0.0
mut f64: _cam_pz = 0.0
mut f64: _vx = 0.0
mut f64: _vy = 0.0
mut f64: _vz = 0.0
mut f64: _h_yaw = 0.0
mut f64: _h_pch = 0.0
mut f64: _target_yaw = 0.0
mut f64: _target_pch = 0.0
mut f64: _sens = 0.08
mut f64: _spd = 500.0
mut f64: _drag = 10.0
mut f64: _damp = 18.0
mut f64: _spdmul = 3.0
mut f64: _p_min = -89.9
mut f64: _p_max = 89.9
mut f64: _spdx = 0.0
mut f64: _spdy = 0.0
mut f64: _spd_z = 0.0
mut bool: _move_w = false
mut bool: _move_a = false
mut bool: _move_s = false
mut bool: _move_d = false
mut bool: _move_space = false
mut bool: _move_shift = false
mut bool: _move_ctrl = false
mut f64: _cam_px_cache = 0.0
mut f64: _cam_py_cache = 0.0
mut f64: _cam_pz_cache = 0.0
mut f64: _cam_fov = 120.0
mut int: fps = 0
mut list: _fps_samples = []
mut int: frame_num = 0
mut int: start_t = 0
mut int: last_upd_t = 0
mut int: last_fps_t = 0
mut int: _last_frame_time = 0
mut f64: _current_frame_time = 0.0
mut f64: _frame_time_accum = 0.0
mut f64: _last_draw_ms = 0.0
mut int: _anim_frame_trace_hits = 0
mut bool: _term_open = false
mut bool: is_ortho = false
mut bool: show_scene = false
mut bool: _cursor_lock_enabled = false
mut bool: _rmb_look_active = false
mut f64: _rmb_look_sens_mul = 0.65
mut f64: _rmb_dx_smooth = 0.0
mut f64: _rmb_dy_smooth = 0.0
mut int: skip_mouse_frames = 0
mut int: total_frames = 0
mut int: _timeout_ns = 0
mut bool: _did_first_frame = false
mut bool: _startup_pumped = false
mut str: active_backend_name = ""
mut any: _axes_mesh = 0
mut int: res_font = 0
mut int: res_font_ui = 0
mut int: res_font_title = 0
mut int: res_font_small = 0
mut any: active_scene = 0
mut str: _loaded_scene_name = ""
mut list: _model_names = []
mut list: _gui_filtered_model_names = []
mut str: _gui_filter_cache_key = "\x00"
mut int: _gui_filter_cache_source_len = -1
mut str: _gui_selected_pick_cache_name = "\x00"
mut str: _gui_selected_pick_cache_filter = "\x00"
mut int: _gui_selected_pick_cache_len = -1
mut int: _gui_selected_pick_cache_idx = -1
mut int: _model_index = -1
mut f64: _win_w = 1280.0
mut f64: _win_h = 720.0
mut f64: _mouse_dx_acc = 0.0
mut f64: _mouse_dy_acc = 0.0
mut int: _intended_cursor_mode = 0
mut f64: _ortho_zoom = 40.0
mut bool: _proj_dirty = true
mut int: _ui_debug_enabled = -1
mut int: _gui_probe_mode = -1
mut int: _gui_probe_overlay_mode = -1
mut int: _fps_log_enabled = -1
mut f64: _cli_timeout_sec = -1.0
mut list: _cli_post_load_cmds = []
mut bool: _cli_scene_requested = false
mut str: _cli_gui_layout = ""
mut str: _cli_gui_shot = ""
mut bool: _cli_dump_requested = false
mut bool: _cli_dump_all_requested = false
mut bool: _cli_dump_missing_requested = false
mut str: _cli_dump_dir = ""
mut str: _cli_batch_models_raw = ""
mut int: _cli_dump_delay_frames = -1
mut str: _cli_gui_auto_dump = ""
mut int: _auto_dump_enabled = 0
mut int: _auto_dump_exit_mode = 0
mut int: _auto_dump_immediate_mode = 0
mut int: _auto_dump_delay_frames = 0
mut int: _auto_dump_frame_counter = 0
mut f64: _auto_dump_min_elapsed_sec = 0.0
mut str: _auto_dump_path = "build/release/fb_dump.png"
mut bool: _auto_dump_done = false
mut bool: _pending_auto_dump = false
mut bool: _batch_dump_active_mode = false
mut int: _batch_dump_index = 0
mut int: _batch_dump_wait_frames = 0
mut list: _batch_dump_models = []
mut list: _batch_dump_model_specs = []
mut list: _batch_dump_skip_models = []
mut str: _batch_dump_dir = ""
mut int: _batch_dump_settle_frames = 4
mut f64: _batch_dump_model_timeout_sec = 45.0
mut int: _batch_dump_model_started_ns = 0
mut int: _batch_dump_run_started_ns = 0
mut int: _batch_dump_load_started_ns = 0
mut int: _batch_dump_completed_count = 0
mut list: _gui_dump_suite_specs = []
mut str: _gui_dump_suite_dir = ""
mut bool: _gui_dump_suite_active = false
mut int: _gui_dump_suite_index = 0
mut int: _gui_dump_suite_wait_frames = 0
mut int: _gui_dump_suite_attempts = 0
mut int: _gui_dump_suite_settle_frames = 4
mut bool: _gui_auto_dump_done = false
mut int: _gui_auto_dump_attempts = 0
mut str: _gui_last_dump_path = ""
mut int: _model_prefetch_thread = 0
mut str: _model_prefetch_name = ""
mut int: _scene_load_async_mu = 0
mut int: _scene_load_async_thread = 0
mut any: _scene_load_async_job = 0
mut str: _scene_load_async_spec = ""
mut str: _scene_load_async_path = ""
mut str: _scene_load_async_display = ""
mut bool: _scene_load_async_auto_frame = true
mut bool: _startup_post_load_pending = false
mut bool: _bench_env_bound = false
mut bool: _bench_cam_bound = false
mut f64: _bench_cam_x = 0.0
mut f64: _bench_cam_y = 0.0
mut f64: _bench_cam_z = 0.0
mut int: skybox_tex_id = -1
mut int: skybox_spec_tex_id = -1
mut any: skybox_im_hold = 0
mut int: compare_env_tex_id = -1
mut int: compare_env_spec_tex_id = -1
mut int: compare_reflect_spec_tex_id = -1
mut int: compare_visible_env_tex_id = -1
mut int: neutral_env_tex_id = -1
mut int: neutral_env_spec_tex_id = -1
mut any: compare_env_im_hold = 0
mut any: compare_reflect_env_im_hold = 0
mut any: compare_visible_env_im_hold = 0
mut any: neutral_env_im_hold = 0
mut bool: skybox_enabled = false
mut bool: _static_world_draw_sky = false
mut int: _static_world_color_reuse_frames = 0
mut int: _static_world_color_reuse_w = 0
mut int: _static_world_color_reuse_h = 0
mut int: _static_world_redraw_frames = 0
mut bool: _startup_skybox_pending = false
mut bool: _anim_enabled = false
mut f64: _anim_time = 0.0
mut int: _anim_idx = 0
mut f64: _anim_speed = 1.0
mut int: _anim_count = 0
mut f64: _anim_duration = 0.0
mut any: _anim_gltf_data = 0
mut int: _skin_count = 0
mut int: _morph_target_count = 0
mut f64: _last_world_ms = 0.0
mut f64: _last_ui_ms = 0.0
mut f64: _last_frame_ms = 0.0
mut f64: _last_update_ms = 0.0
mut f64: _last_evt_ms = 0.0
mut f64: _last_gui_prep_ms = 0.0
mut f64: _last_sim_ms = 0.0
mut list: M_ID = rmat.mat4_identity()
mut list: M_UI_OVERLAY = rmat.mat4_identity()
mut list: M_W = rmat.mat4_identity()
mut list: M_PT = rmat.mat4_identity()
mut list: M_PR = rmat.mat4_identity()
mut list: M_PS = rmat.mat4_identity()
mut list: M_PW = rmat.mat4_identity()
mut list: M_Ptmp = rmat.mat4_identity()
mut list: M_V = rmat.mat4_identity()
mut list: M_P = rmat.mat4_identity()
mut list: M_VP = rmat.mat4_identity()
mut list: M_V_SKY = rmat.mat4_identity()
mut list: M_VP_SKY = rmat.mat4_identity()
mut list: M_SP = rmat.mat4_identity()
mut any: _crosshair_mesh = 0
mut any: _crosshair_buf = 0
mut f64: _cross_cx_last = -9e9
mut f64: _cross_cy_last = -9e9
mut list: M_cross_t = rmat.mat4_identity()
mut f64: _last_cam_px = -9e9
mut f64: _last_cam_py = -9e9
mut f64: _last_cam_pz = -9e9
mut f64: _last_cam_tx = -9e9
mut f64: _last_cam_ty = -9e9
mut f64: _last_cam_tz = -9e9
mut int: _last_draw_world_state = -1
mut str: _last_world_parity_sig = ""
mut str: _last_editor_parity_sig = ""
mut int: _last_term_open_state = -1
mut str: _ui_update_stage = ""
mut bool: _gui_visible = false
mut bool: _gui_show_editor = false
mut bool: _gui_probe_overlay = false
mut bool: _gui_show_gallery = false
mut bool: _gui_show_probe = false
mut bool: _gui_show_browser = false
mut bool: _gui_show_profiler = false
mut bool: _gui_show_workspace = false
mut bool: _gui_show_graph = false
mut bool: _gui_show_inspector = false
mut f64: _gui_scale = 1.0
mut f64: _gui_dpi_scale = 1.0
mut bool: _gui_scale_manual = false
mut list: _gui_accent = [0.86, 0.86, 0.86, 0.96]
mut str: _gui_last_probe_text = ""
mut str: _gui_shot_name = ""
mut str: _gui_console_input = ""
mut bool: _scene_selected = false
mut bool: _scene_selection_rect = true
mut bool: _scene_drag_active = false
mut int: _scene_drag_mode = 0
mut dict: _scene_drag_state = dict(0)
mut int: _gizmo_mode = 0
mut int: _gizmo_axis = 0
mut bool: _gizmo_snap = false
mut bool: _gizmo_precise = false
mut bool: _gizmo_ruler = true
mut list: _scene_selection_cached_bounds = []
mut str: _scene_selection_cached_name = ""
mut list: _selection_overlay_panel_rect = [0.0, 0.0, 0.0, 0.0]
mut list: _selection_overlay_toolbar_rect = [0.0, 0.0, 0.0, 0.0]
mut list: _selection_overlay_move_rect = [0.0, 0.0, 0.0, 0.0]
mut list: _selection_overlay_rotate_rect = [0.0, 0.0, 0.0, 0.0]
mut list: _selection_overlay_scale_rect = [0.0, 0.0, 0.0, 0.0]
mut int: _selection_overlay_hover_mode = -1
mut int: _selection_overlay_dump_mode = 0
mut int: _gui_editor_tab = 0
mut int: _gui_gallery_tab = 0
mut int: _gui_browser_tab = 0
mut int: _gui_inspector_tab = 1
mut int: _gui_workspace_mode = 1
mut int: _gui_center_tab = 0
mut int: _gui_side_tab = 0
mut int: _gui_layout_slot_idx = 0
mut int: _gui_env_mode = 0
mut bool: _gui_demo_toggle_a = true
mut bool: _gui_demo_toggle_b = false
mut int: _gui_demo_radio = 0
mut int: _gui_demo_combo = 0
mut f64: _gui_demo_progress = 0.25
mut f64: _gui_demo_float = 1.0
mut int: _gui_demo_int = 0
mut str: _gui_model_filter = ""
mut str: _gui_model_selected_name = ""
mut bool: _gui_model_show_paths = false
mut f64: _gui_workspace_grid = 32.0
mut int: _gui_workspace_major = 4
mut list: _gui_graph_nodes = []
mut list: _gui_graph_links = []
mut str: _scene_pref_cache_name = "\x00"
mut bool: _scene_pref_studio = false
mut bool: _scene_pref_neutral = false
mut bool: _scene_pref_reflect = false
mut bool: _scene_pref_visible = false
mut bool: _scene_pref_optical = false
mut bool: _scene_pref_black_visible = false
mut list: _frame_ms_samples = []
mut list: _draw_ms_samples = []
mut list: _world_ms_samples = []
mut list: _ui_ms_samples = []
mut list: _update_ms_samples = []
mut dict: _gui_frame_stats_cache = dict(0)
mut int: _gui_scene_parts_cache = 0
mut str: _gui_renderer_hotspot_cache = ""
mut int: _gui_frame_stats_refresh_frame = -999999
mut bool: _gui_layout_dirty = true
mut int: _gui_layout_warm_frames = 0
mut f64: _gui_layout_gap = 0.0
mut f64: _gui_layout_last_w = -1.0
mut f64: _gui_layout_last_h = -1.0
mut str: _gui_layout_preset_name = ""
mut bool: _gui_probe_bootstrapped = false
mut bool: _hotkey_f1_down = false
mut int: _hotkey_f1_last_ns = 0
mut int: _hotkey_text_suppress_until_ns = 0
mut list: _gui_editor_tab_items = ["Catalog", "Hierarchy", "Theme", "Console"]
mut list: _gui_layout_preset_items = ["default", "probe", "graph", "compact"]
mut list: _gui_env_mode_items = ["Auto", "Studio", "Neutral", "Raw Sky", "None"]
mut list: _gui_msaa_items = ["1x off", "2x", "4x", "8x"]
mut list: _gui_browser_tab_items = ["Catalog", "Hierarchy"]
mut list: _gui_layout_slot_items = ["Slot 1", "Slot 2", "Slot 3", "Slot 4"]
mut list: _gui_layout_slots = [0, 0, 0, 0]
mut list: _gui_shot_preset_items = [
   "full_editor",
   "full_editor_workspace",
   "editor_catalog",
   "editor_hierarchy",
   "editor_scene",
   "editor_scene_compact",
   "editor_view",
   "editor_probe",
   "gallery_basics",
   "browser_catalog",
   "inspector_scene", "inspector_settings",
   "graph", "profiler"
]

mut list: _gui_demo_context_items = [
   "Scene Editing", "Material Authoring", "Animation", "Lighting",
   "Profiling", "Build / Export", "Automation", "Validation"
]

mut f64: _render_phase = 0.0
mut f64: _render_dt = 0.0
