use std.core
use std.core.error
use std.core.iter as it

assert(it.range(5) == [0, 1, 2, 3, 4], "range stop")
assert(it.range(2, 6) == [2, 3, 4, 5], "range start stop")
assert(it.range(5, 0) == [], "range stop zero two-arg")
assert(it.range(0, 0) == [], "range zero zero")
assert(it.range(6, 2, -2) == [6, 4], "range step")
assert(it.range2(1, 8, 3) == [1, 4, 7], "range2")
assert(is_range(it.range(1)), "range predicate")
assert(__tagof(it.range(1)) == __runtime_tag("range"), "range runtime tag")
assert(it.enumerate(["a", "b"], 10) == [[10, "a"], [11, "b"]], "enumerate")
assert(it.map([1, 2, 3], fn(v) { v * v }) == [1, 4, 9], "map list")
assert(it.map("ab", fn(v) { v + "!" }) == "a!b!", "map string")
assert(it.filter([1, 2, 3, 4, 5, 6], fn(v) { (v % 2) == 0 }) == [2, 4, 6], "filter list")
assert(it.filter("aaba", fn(v) { v >= "a" }) == "aaba", "filter string")
assert(it.repeat("x", 3) == ["x", "x", "x"], "repeat")
assert(it.take([9, 8, 7], 2) == [9, 8], "take list")
assert(it.take("abcd", 2) == "ab", "take string")
assert(it.drop([9, 8, 7], 1) == [8, 7], "drop list")
assert(it.drop("abcd", 2) == "cd", "drop string")
assert(it.take([], 3) == [], "take empty list")
assert(it.take("", 3) == "", "take empty string")
assert(it.take([7], 1) == [7], "take single item list")
assert(it.take("z", 1) == "z", "take single item string")
assert(it.drop([], 1) == [], "drop empty list")
assert(it.drop("", 1) == "", "drop empty string")
assert(it.drop([7], 1) == [], "drop single item list")
assert(it.drop("z", 1) == "", "drop single item string")
assert(it.reverse([1, 2, 3]) == [3, 2, 1], "reverse list")
assert(it.reverse("abc") == "cba", "reverse string")
assert(it.reverse([]) == [], "reverse empty list")
assert(it.reverse("") == "", "reverse empty string")
assert(it.reverse([5]) == [5], "reverse single item list")
assert(it.reverse("q") == "q", "reverse single item string")
assert(it.zip2(["a", "b", "c"], [1, 2]) == [["a", 1], ["b", 2]], "zip2")
assert(it.any([1, 2, 3], fn(v) { v > 2 }), "any true")
assert(!it.any([1, 2, 3], fn(v) { v > 5 }), "any false")
assert(it.all([4, 5, 6], fn(v) { v > 3 }), "all true")
assert(!it.all([4, 5, 6], fn(v) { v > 5 }), "all false")
assert(it.fold([1, 2, 3, 4], 0, fn(a, v) { a + v }) == 10, "fold")
assert(it.reduce([1, 2, 3], 1, fn(a, v) { a * v }) == 6, "reduce")
assert(it.count([1, 2, 3]) == 3, "count")
assert(it.count_if([1, 2, 3, 4], fn(v) { v > 2 }) == 2, "count if")
assert(it.first([10, 20], -1) == 10, "first")
assert(it.first([], -1) == -1, "first default")
assert(it.last([10, 20], -1) == 20, "last")
assert(it.last([], -1) == -1, "last default")
assert(it.find_if([10, 20, 30], fn(v) { v > 15 }) == 20, "find")
assert(it.find_if([10, 20, 30], fn(v) { v > 50 }, -1) == -1, "find missing")
assert(it.find_index_if([10, 20, 30], fn(v) { v > 15 }) == 1, "find index")
assert(it.chain([1, 2], [3, 4]) == [1, 2, 3, 4], "chain list")
assert(it.chain("ab", "cd") == "abcd", "chain string")
assert(it.chain([], []) == [], "chain empty lists")
assert(it.chain("", "") == "", "chain empty strings")
assert(it.chain([], [4, 5]) == [4, 5], "chain left empty list")
assert(it.chain([4, 5], []) == [4, 5], "chain right empty list")
assert(it.flatten([[1, 2], 3, [4, 5]]) == [1, 2, 3, 4, 5], "flatten")
assert(it.flatten([(1, 2), it.range(2), "ab"]) == [1, 2, 0, 1, "a", "b"], "flatten sequences")
assert(it.mapcat(fn(v) { [v, v] }, [1, 2]) == [1, 1, 2, 2], "mapcat")
assert(it.mapcat(fn(v) { v }, [(1, 2), "ab", it.range(2)]) == [1, 2, "a", "b", 0, 1], "mapcat sequences")
assert(it.filter_map([1, 2, 3, 4], fn(v) {
         if((v % 2) == 0){ return v * 10 }
         0
}) == [20, 40], "filter map")
assert(it.compact([0, 1, "", "x", nil, 4]) == [1, "x", 4], "compact")
assert(it.zip_with([1, 2], [10, 20], fn(a, b) { a + b }) == [11, 22], "zip with")
assert(it.cycle([1, 2], 3) == [1, 2, 1, 2, 1, 2], "cycle")
assert(it.chunk([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]], "chunk list")
assert(it.chunk("abcde", 2) == ["ab", "cd", "e"], "chunk string")
assert(it.windowed([1, 2, 3, 4], 3) == [[1, 2, 3], [2, 3, 4]], "windowed list")
assert(it.windowed("abcd", 2, 2) == ["ab", "cd"], "windowed string")
assert([1, 2, 3].map(fn(v) { v + 1 }) == [2, 3, 4], "list map method")
assert([1, 2, 3, 4].filter(fn(v) { v % 2 == 0 }) == [2, 4], "list filter method")
assert([1, 2, 3].reduce(0, fn(a, v) { a + v }) == 6, "list reduce method")
assert("abcd".chunk(2) == ["ab", "cd"], "str chunk method")
assert((1, 2, 3).first(-1) == 1, "tuple first method")
def pt = it.partition([1, 2, 3, 4, 5], fn(v) { v > 3 })
assert(pt.get(0) == [4, 5], "partition true")
assert(pt.get(1) == [1, 2, 3], "partition false")
assert([1, 2, 3].get(-1, 0) == 3, "get list negative index")
assert("abc".get(-1, "") == "c", "get string negative index")
assert([1, 2, 3].get(9, 77) == 77, "get list out of range default")
assert("abc".get(9, "?") == "?", "get string out of range default")
assert(slice([1, 2, 3], 0, 0) == [], "slice empty list range")
assert(slice("abc", 0, 0) == "", "slice empty string range")
assert(values(it.range(5, 0, -1)) == [5, 4, 3, 2, 1], "values range")
assert(keys(it.range(5, 0, -1)) == [0, 1, 2, 3, 4], "keys range")
assert(items(it.range(5, 0, -1)) == [[0, 5], [1, 4], [2, 3], [3, 2], [4, 1]], "items range")
assert(sort(it.range(5, 0, -1)) == [1, 2, 3, 4, 5], "sort range")
assert(sorted(it.range(5, 0, -1)) == [1, 2, 3, 4, 5], "sorted range")
def fruits = [1, 2, 3, 4]
mut weighted = 0
for fruit, i in fruits {
   weighted += fruit * (i + 1)
}

assert(weighted == 30, "for value,index over list")
mut letters = []
for x, i in "test" {
   letters = letters.append(f"{x}:{i}")
}

assert(letters == ["t:0", "e:1", "s:2", "t:3"], "for value,index over string")
print("✓ std.core.iter runtime tests passed")
