use std.core

def p = malloc(8)
assert(p != 0, "malloc")
memset(p, 0, 8)
store8(p, 65, 0)
store8(p, 66, 1)
assert(load8(p, 0) == 65, "load8 first byte")
assert(load8(p, 1) == 66, "load8 second byte")
assert(memchr(p, 66, 8) == ptr_add(p, 1), "memchr")
def q = malloc(8)
memset(q, 0, 8)
memcpy(q, p, 8)
assert(memcmp(p, q, 8) == 0, "memcpy + memcmp")
def r = realloc(q, 16)
assert(r != 0, "realloc")
assert(load8(r, 0) == 65, "realloc keeps first byte")
assert(load8(r, 1) == 66, "realloc keeps second byte")
free(p, r)
def a = malloc(1)
def b = malloc(1)
def c = malloc(1)
assert(a != 0 && b != 0 && c != 0, "variadic free malloc")
free(a, b, 0, c)
assert(__release_owned(nil) == nil, "__release_owned accepts nil")
assert(__drop_owned_slot(0) == nil, "__drop_owned_slot rejects tagged zero")
assert(__runtime_cleanup() == nil, "__runtime_cleanup returns nil")
print("✓ memory tests passed")
